export const APP_ICONS = {
  activity: 'user-friends',
  activityClose: 'hourglass-end',
  activityOpen: 'hourglass-start',
  configure: 'cogs',
  copy: 'copy',
  consumer: 'graduation-cap',
  course: 'chalkboard-teacher',
  download: 'download',
  edit: 'edit',
  ehrPage: 'book-medical',
  exitToLms: 'sign-out-alt',
  file: 'notes-medical',
  filter: 'filter',
  forceSubmit: 'lock',
  retractSubmit: 'unlock',
  list: 'list',
  lobj: 'book-open',
  menu: 'bars',
  new: 'magic',
  seed: 'hand-holding-medical',
  returnToSeedList: 'list',
  rawEhr: 'th-large',
  tags: 'tag', // for filtering by tag applied to an object
  trash: 'trash',
  undo: 'undo',
  view: 'eye',

}