<template lang="pug">
  div(:class="$options.name")
    bread-crumb(currentPage="assignments")
    h1 Learning Objects
    div(v-if="isRespondingToError")
      p Error: {{ isRespondingToError }}
      p Your LMS is asking for "{{ activity.custom_assignment }}".
      p Ask your learning management system administrator to use a learning object from the list below
    div(v-show="isDevelopingContent")
      ui-button(v-on:buttonClicked="showCreateDialog") Create a new learning object
      ui-button(v-on:buttonClicked="downloadAll") Download all learning objects
    div(v-if="validationWarning")
      p(class="un-configured-warning") Shaded items below may need some review and edits.

    div(class="seedData-list-body")
      div(v-for="item in assignmentsListing", class="card list-element", :class="rowClass(item)")
        div(class="columns")
          div(class="column is-2 key") {{cText.LO.nameLabel}}
          div(class="column is-10 value") {{item.name}}
        div(v-show="isDevelopingContent", class="columns")
          div(class="column is-2 key") Learning object id
          div(class="column is-10 value") {{ item.externalId}}
        div(class="columns")
          div(class="column is-2 key") Description
          div(class="column is-10 value")
            div(v-if="item.description.length > 0", v-text-to-html="item.description")
            div(v-else) {{ item.description }}
        div(class="columns")
          div(class="column is-2 key") Used by
          div(class="column is-10 value") {{ activitiesUsingAssignmentCount(item._id) }} activities
        div(class="columns")
          div(class="column is-2 key") Seed data object
          div(class="column is-10 value")
            ui-link(:name="'developEhrData'", :params="{seedId: item.seedDataObj._id}") {{ item.seedDataObj.name }}
        div(class="columns")
          div(class="column is-2 key") Created
          div(class="column is-10 value") {{item.createDate | formatDateTime}}
        div(class="columns")
          div(class="column is-2 key") Last Update
          div(class="column is-10 value") {{item.lastUpdateDate | formatDateTime}}
        div(v-show="isDevelopingContent", class="columns")
          div(class="column" align="right")
            div(class="column is-10 value")
              ui-button(v-on:buttonClicked="showEditDialog", :value="item._id", :secondary="isItemMisconfigured(item)")
                fas-icon(icon="edit") Edit learning object properties
                  //- , v-on:buttonClicked="showDeleteConfirmDialog", :value="item._id",
              ui-button(v-if="canBeDeleted(item)", danger, @buttonClicked="triggerConfirmDeletion(item)")
                fas-icon(icon="trash")  Edit learning object properties
    assignments-dialog(ref="theDialog")
    ui-confirm(ref="confirmDialog", @confirm="handleDeletion", @abort="resetDeletion", @cancel="resetDeletion", saveLabel="Confirm")
    
</template>

<script>
import EventBus, { PAGE_DATA_REFRESH_EVENT } from '@/helpers/event-bus'
import UiButton from '../../app/ui/UiButton.vue'
import UiLink from '../../app/ui/UiLink.vue'
import UiConfirm from '../../app/ui/UiConfirm'
import StoreHelper from '../../helpers/store-helper'
import { downObjectToFile, getIncomingParams } from '@/helpers/ehr-utils'
import BreadCrumb from './BreadCrumb'
import AssignmentsDialog from './AssignmentsDialog'
import { Text } from '@/helpers/ehr-text'

// These constants must be kept in sync with the ones defined in the backend
// in ../src/config/text.js. Please, make sure they're the same, in case of change
const DEFAULT_ASSIGNMENT_DESCRIPTION = 'This learning object was automatically generated by an LTI request. Please update the description by editing in the EdEHR.'
const DEFAULT_SEED_NAME = 'Default data'
const DEFAULT_SEED_DESCRIPTION = 'This EHR seed data can not be modified. It is the default seed used when any learning object is created'

const CONFIRM_DELETION_TEXT = {
  title: 'Confirm deletion of learning object?',
  description: (name) => `Deleting ${name} will also delete all the data related to it.`
}

const debug = false

const learningObjectHasDefaultProperty = function (item) {
  return item.description === DEFAULT_ASSIGNMENT_DESCRIPTION ||
  DEFAULT_SEED_NAME === item.seedDataObj.name ||
  DEFAULT_SEED_DESCRIPTION === item.seedDataObj.description
}

export default {
  name: 'AssignmentsListing',
  data () {
    return {
      isRespondingToError: null,
      isAdmin: false,
      selectedAssignment: {}
    }
  },
  components: { AssignmentsDialog, UiButton, UiConfirm, UiLink, BreadCrumb },
  computed: {
    cText () { return Text },
    validationWarning () {
      const list = StoreHelper.getAssignmentsList()
      return list.find(element => learningObjectHasDefaultProperty(element))

    },
    isDevelopingContent () {
      return StoreHelper.isDevelopingContent()
    },
    activity () {
      return {custom_assignment:'This error handling feature is a work in progress'}
    },
    assignmentsListing () { return StoreHelper.getAssignmentsList()}
  },

  methods: {
    rowClass: function (item) {
      let selected = item._id === this.$route.params.assignmentId
      let classString = selected ? 'selected ' : ''
      const isWarning = this.isItemMisconfigured(item) ? 'un-configured' : ''
      return `${classString}${isWarning}`
    },
    activitiesUsingAssignmentCount: function (assignmentId) {
      return StoreHelper.activitiesUsingAssignmentCount(assignmentId)
    },
    downloadAll () {
      StoreHelper.loadAssignmentList(this)
        .then((aList) => {
          downObjectToFile('EdEHR-assignments-list.json', aList)
        })
    },

    findAssignment: function (id) {
      return this.assignmentsListing.find(e => {
        return e._id === id
      })
    },
    showEditDialog: function (event, assignmentId) {
      let assignmentData = Object.assign({}, this.findAssignment(assignmentId))
      this.$refs.theDialog.showDialog(assignmentData)
    },
    showCreateDialog: function () {
      this.$refs.theDialog.showDialog()
    },
    isItemMisconfigured (item) {
      return learningObjectHasDefaultProperty(item)
    },
    canBeDeleted (item) {
      const count = this.activitiesUsingAssignmentCount(item._id)
      return this.isAdmin && count === 0
    },
    triggerConfirmDeletion (item) {
      this.selectedAssignment = item
      this.$refs.confirmDialog.showDialog(
        CONFIRM_DELETION_TEXT.title,
        CONFIRM_DELETION_TEXT.description(item.name),
        'Confirm',
        'Cancel'
      )
    },
    handleDeletion () {
      StoreHelper.deleteAssignment(this.selectedAssignment._id)
        .then(() => {
          StoreHelper.setLoading(null, true)
          StoreHelper.loadAssignmentList()
          StoreHelper.setLoading(null, false)
        })
    },
    resetDeletion (item) {
      this.selectedAssignment = {}
    },
    loadComponent () {
      // TODO BG thinks this needs to be tested. Create a LMS activity with invalid external id.
      // Need to give error to user. Does this do it?
      let params2 = getIncomingParams()
      this.isRespondingToError = params2['error']
      StoreHelper.loadAssignmentList()
      StoreHelper.adminValidate()
        .then(r => {
          if (debug) console.log('AssignmentsListing admin validate', r)
          this.isAdmin = r.isAdmin
        }).catch(err => {
          if (debug) console.log('AssignmentsListing not admin', err)
        })
    }
  },
  created: function () {
    /*
      Must wait for App to load auth before loading this component
     */
    const _this = this
    this.refreshEventHandler = function () { _this.loadComponent() }
    EventBus.$on(PAGE_DATA_REFRESH_EVENT, this.refreshEventHandler)
  },
  beforeDestroy: function () {
    if (this.refreshEventHandler) {
      EventBus.$off(PAGE_DATA_REFRESH_EVENT, this.refreshEventHandler)
    }
  },
}
</script>

<style lang="scss" scoped>
@import '../../scss/definitions';
.list-element {
  padding: 1rem 1.5rem;
  margin-bottom: 1rem;
}
.key {
  font-weight: bold;
}
.key::after {
  content: ': '
}

.un-configured {
  background: $greyWarn;
  opacity: 0.8;
}

.un-configured-warning {
  color: $grey80;
}

</style>
