<template lang="pug">
  div(:class="$options.name")
    bread-crumb(currentPage="assignments")
    h1 Assignments
    div(v-if="isRespondingToError")
      p Error: {{ isRespondingToError }}
      p Your LMS is asking for "{{ activity.custom_assignment }}".
      p Adjust your Learning Management System to use an assignment from the list below
    div(v-show="isDevelopingContent")
      ui-button(v-on:buttonClicked="showCreateDialog") Create a new assignment
      ui-button(v-on:buttonClicked="downloadAll") Download all assignments
      ui-button(v-on:buttonClicked="manageEhrData", :secondary="true") Manage seed data
    div(v-if="validationWarning")
      p(class="un-configured-warning") {{ validationWarning }}
    table.table
      thead
        tr
          th(title="Name", style="min-width: 170px") Assignment name
          th(title="Description") Description
          th(title="Activities") Activities
          th(title="External Id", style="min-width: 110px") External id
          // th(title="Route") Route
          th(title="Seed Data", style="min-width: 170px") Seed name
          th
      tbody
        tr(v-for="item in assignmentsListing", :class="rowClass(item)")
          td {{ item.name }}
          //- The following conditional flow is needed because 
          //- v-text-to-html can be kept out of sync when 
          //- clearing the description value
          td(v-if="item.description.length > 0")
            div(v-text-to-html="item.description") 
          td(v-else) {{ item.description }}
          td {{ activitiesUsingAssignmentCount(item._id) }}
          td {{ item.externalId}}
          td
            ui-link(:name="'developEhrData'", :params="{seedId: item.seedDataObj._id}") {{ item.seedDataObj.name }}
          td
            ui-button(v-on:buttonClicked="showEditDialog", :value="item._id", :secondary="isItemMisconfigured(item)")
              fas-icon(icon="edit") Edit assignment properties
            //- , v-on:buttonClicked="showDeleteConfirmDialog", :value="item._id", 
            ui-button(v-if="canBeDeleted(item)", danger )
              fas-icon(icon="trash")  Edit assignment properties
    assignments-dialog(ref="theDialog")
    ui-confirm(ref="confirmDialog", @confirm="handleDeletion", @abort="resetDeletion", @cancel="resetDeletion")
    
</template>

<script>
import UiButton from '../../app/ui/UiButton.vue'
import UiLink from '../../app/ui/UiLink.vue'
import UiConfirm from '../../app/ui/UiConfirm'
import StoreHelper from '../../helpers/store-helper'
import { getIncomingParams, downObjectToFile } from '../../helpers/ehr-utils'
import BreadCrumb from './BreadCrumb'
import AssignmentsDialog from './AssignmentsDialog'

// These constants must be kept in sync with the ones defined in the backend
// in ../src/config/text.js. Please, make sure they're the same, in case of change
const DEFAULT_ASSIGNMENT_DESCRIPTION = 'This assignment was automatically generated by an LTI request. Please update this description by editing the assignment in the EdEHR.'
const DEFAULT_SEED_NAME = 'Default data'
const DEFAULT_SEED_DESCRIPTION = 'This ehr data seed can not be modified. It is the default seed used when an assignment is created'

export default {
  name: 'AssignmentsListing',
  data () {
    return {
      isRespondingToError: null,
      validationWarning: null,
      isAdmin: false
    }
  },
  components: { AssignmentsDialog, UiButton, UiConfirm, UiLink, BreadCrumb },
  computed: {
    isDevelopingContent () {
      return StoreHelper.isDevelopingContent()
    },
    activity () {
      return {custom_assignment:'This error handling feature is a work in progress'}
    },
    assignmentsListing () { return StoreHelper.getAssignmentsList()}
  },

  methods: {
    rowClass: function (item) {
      let selected = item._id === this.$route.params.assignmentId
      let classString = selected ? 'selected ' : ''
      const isWarning = this.isItemMisconfigured(item) ? 'un-configured' : ''
      return `${classString}${isWarning}`
    },
    activitiesUsingAssignmentCount: function (assignmentId) {
      return StoreHelper.activitiesUsingAssignmentCount(assignmentId)
    },
    manageEhrData: function () {
      this.$router.push('developEhrData')
    },
    downloadAll () {
      StoreHelper.loadAssignmentList(this)
        .then ( (aList) => {
          downObjectToFile('EdEHR-assignments-list.json', aList)
        })
    },

    findAssignment: function (id) {
      return this.assignmentsListing.find(e => {
        return e._id === id
      })
    },
    showEditDialog: function (event, assignmentId) {
      let assignmentData = Object.assign({}, this.findAssignment(assignmentId))
      this.$refs.theDialog.showDialog(assignmentData)
    },
    showCreateDialog: function () {
      this.$refs.theDialog.showDialog()
    },
    isItemMisconfigured (item) {
      this.validationWarning = 'Shaded rows need further configuration. '
      return item.description === DEFAULT_ASSIGNMENT_DESCRIPTION || 
      DEFAULT_SEED_NAME === item.seedDataObj.name || 
      DEFAULT_SEED_DESCRIPTION === item.seedDataObj.description
    },
    canBeDeleted (item) {
      const count = this.activitiesUsingAssignmentCount(item._id)
      return this.isAdmin && count === 0
    },

    handleDeletion (item) {

    },
    
    resetDeletion (item) {
      
    }
  },
  mounted: function () {
    const debug = true
    // TODO BG thinks this needs to be tested. Create a LMS activity with invalid external id.
    // Need to give error to user. Does this do it?
    let params2 = getIncomingParams()
    this.isRespondingToError = params2['error']
    StoreHelper.loadAssignmentList()
    const token = StoreHelper.getAuthToken()
    StoreHelper.adminValidate(token)
      .then(r => {
        if (debug) console.log('r >> ', r)
        this.isAdmin = r.isAdmin
      }).catch(err => {
        if (debug) console.log('err')
      })

  }
}
</script>

<style lang="scss" scoped>
@import '../../scss/_definitions';
.un-configured {
  background: $greyWarn;
  opacity: 0.8;
}

.un-configured-warning {
  color: $grey80;
}

</style>
